### ISSUE TITLE
[FEATURE] Channel Selection

### ISSUE THREAD

**Issue by bellyrose** [YunzheZJU/holo-schedule#105]
An option to configure which channels show up in the feed would be nice. Maybe a favorites system to show selected channels' streams in a category above the rest.

**Comment by YunzheZJU** [comment]
Hi,
To find the member list and change the subscriptions, please click the 'options' icon at the top-right corner and then go to 'Advanced Settings' which would open a page for editing subscriptions.

**Comment by bellyrose** [comment]
Oh, didn't notice that if it was already a thing, thanks!
