### ISSUE TITLE
[FEATURE] Navigate directly to TwitterSpace (not peek)

### ISSUE THREAD

**Issue by HitomaruKonpaku** [YunzheZJU/holo-schedule#123]
**Is your feature request related to a problem? Please describe.**
Same as title

**Describe the solution you'd like**
Remove `/peek` in `constructUrl`

**Additional context**
Clicking on TwitterSpace link (browser) should directly navigate user to Space (not peek)

Should be
![image](https://user-images.githubusercontent.com/9608105/150633034-b8c2d017-8e34-416d-b361-0be7e527d26d.png)

Instead of
![image](https://user-images.githubusercontent.com/9608105/150633040-249069b5-3c37-40f9-ba01-575339675046.png)

**Comment by YunzheZJU** [comment]
You are right. Though `/peek` gives richer contents for an undergoing Twitter Space, it does not have the function to play the recording.
