### ISSUE TITLE
[BUG] Firefox Nightly

### ISSUE THREAD

**Issue by HDark15** [YunzheZJU/holo-schedule#151]
Can't click "REMIND ME" and there's no profile picture

The console show
`DOMException: Proxy object could not be cloned.`

 - OS: Windows 10
 - Browser: Firefox Nightly
 - Version: 120.0a1

**Comment by YunzheZJU** [comment]
I will have a look.
Thank you for report.

**Comment by YunzheZJU** [comment]
This issue has been confirmed.

The buggy code is located at https://github.com/YunzheZJU/holo-schedule/blob/master/src/shared/browser/index.js#L5 where `typeof InstallTrigger === 'undefined'` is evaluated to be `true` in the Firefox Nightly build 120.0a1.

I am going to find another way to detect the browser vendor, for switching behaviors when sending and receiving messages with ports.

**Comment by YunzheZJU** [comment]
It may take several days for Firefox to deliver the fix to users.
Sorry for the inconvenience.
