### ISSUE TITLE
holo.dev

### ISSUE THREAD

**Issue by romdej** [YunzheZJU/holo-schedule#154]
First and foremost, I would like to extend my apologies for this issue, which is not directly related to the project.

I would like to get in touch with you to inquire if you would be willing to transfer ownership of your domain holo.dev. I have an ambitious project in mind that would greatly benefit from having this domain name. That's why I'm ready to purchase it from you.

If you're interested, please inform me, and I will provide you with my contact information so we can discuss this further.

**Comment by YunzheZJU** [comment]
The owner of that domain has no interest in selling it. Sorry for the inconvenience.
