### ISSUE TITLE
[BUG] is the schedule for elizabeth bloodflame working?

### ISSUE THREAD

**Issue by ZANdewanai** [YunzheZJU/holo-schedule#159]
**Describe the bug**
whenever i check for her scheduled lives she just isnt there in the extension, was wondering if it would update in time but has been quite a while now and havent seen any changes, but maybe thats only me.

**To Reproduce**
1. Go to 'one of elizabeth's scheduled lives https://www.youtube.com/@holoen_erbloodflame'
2. Click on 'the holoschedule extension to see if its marked as a scheduled live'
3. Scroll down to 'see if there is anything there'

**Expected behavior**
A Elizabeth Rose Bloodflame scheduled live appears in the extension

**Screenshots**
![image](https://github.com/YunzheZJU/holo-schedule/assets/68141931/ad9ebb50-7570-4bd1-ac87-5483b6acde58)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Opera]
 - Version [111.0.5168.54]

**Additional context**
i noticed it from their debut onwards but was thinking it would be updated like with the other girls so far, sad it wasnt

**Comment by ZANdewanai** [comment]
should look something like this as seen in the hololive official schedule, in this case
![image](https://github.com/YunzheZJU/holo-schedule/assets/68141931/4940d611-4ae4-44d8-916e-5d0efe9cd1b7)

**Comment by ZANdewanai** [comment]
also tested it in chrome version 126.0.6478.127
if opera is not your cup of tea

![image](https://github.com/YunzheZJU/holo-schedule/assets/68141931/15a0499b-9b15-42ca-9613-0edcba81cf97)

**Comment by ZANdewanai** [comment]
also also, when it hit 10 mins for the live it marked it as a "guerrilla live" too, and sent me a notification for it
even though it was a scheduled one
![image](https://github.com/YunzheZJU/holo-schedule/assets/68141931/3ef59225-9cf8-4d1b-925b-c1f6515ce0b8)

**Comment by ZANdewanai** [comment]
seems now there is a scheduled live showing so maybe its was some random thing that may or may not happen from time to time, so i'll close the issue with that
![image](https://github.com/YunzheZJU/holo-schedule/assets/68141931/4c3a4ca3-c950-4e76-8491-ca8fcf0372f1)

**Comment by YunzheZJU** [comment]
Sorry for your bad experience.

For now, the data source of youtube lives for HoloSchedule originates from the exact contents on the channel's homepage. As long as the scheduled live shows up for some minutes, we know that.

For some reasons from youtube or channels owner's config, some scheduled contents like Premiere Videos or lives just reject to show up. In this case, the owner's official Twitter account is acknowledged as a fallback source. Sadly, if the tweet is not published in time, the newly found content would be viewed as a guerrilla live.

We are thankful to you for reporting what you have seen. This would help us with improving the quality of identification. 

By the way, would you please share the origin of your second screenshot? The layout is clean and clear, which cannot be found in scheduled.hololive.tv or HoloPlus app.

**Comment by ZANdewanai** [comment]
https://hololive.hololivepro.com/en/schedule here you go!
