### ISSUE TITLE
[FEATURE] Go to "Live" streams by default

### ISSUE THREAD

**Issue by LittleVulpix** [YunzheZJU/holo-schedule#67]
**Is your feature request related to a problem? Please describe.**
Currently, when I open holo-schedule, it defaults to list of all streams for the day.

**Describe the solution you'd like**
There could be a setting in the advanced settings where one could select which "section" should open by default.

**Describe alternatives you've considered**
Currently, I have to click the "Live" bookmark in the addon to go to the start of the list of livestreams. It's not too problematic but it is one needless click

**Additional context**
It feels like it wasn't the case, several versions prior, but I cannot say for sure.

**Comment by YunzheZJU** [comment]
Hi, LittleVulpix! Thank you for your feedback and I'm sorry that I missed the notification of this issue.

I've also noticed the situation you've described.

~~When holo-schedule is opened, like any other webpage, the first item of 'ended lives' aligns to the top of the extensions's popup window. Then holo-schedule will send a call to the browser, which requests it to scroll the window to an position where the 'Live' bookmark is displayed. Though most browsers can perform this job well, they are too 'lazy' to align that 'Live' bookmark to the top of the window. This causes one needless click or manual scroll when there are several ended lives already loaded.~~ << That's not the fact.

My original idea is exactly scroll the container and display the current lives as you've described but it does not work as expected. After checked the codebase, I found this behavior is not controlled carefully. I will work on this issue and throw further updated here.

Feel free here and thank you again for your contribution!

**Comment by YunzheZJU** [comment]
I have proposed a fix for this issue. When it is merged into master, it may take another few days for holo-schedule to release a new version and pass the audit from the stores.

**Comment by LittleVulpix** [comment]
Thank you so much! I'm looking forward to the next release, then!

**Comment by LittleVulpix** [comment]
Thanks! It works - I just updated!

**Comment by YunzheZJU** [comment]
> Thanks! It works - I just updated!

Glad u like it ;)
